//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreamingCourses_Implementations.Resourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Pages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StreamingCourses_Implementations.Resourses.Pages", typeof(Pages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Куратор&lt;/strong&gt;: &lt;i&gt;{0} {1}. &lt;/i&gt;
        ///
        ///&lt;strong&gt;Разница с Мск&lt;/strong&gt;: &lt;i&gt;{2}&lt;/i&gt;
        ///
        ///&lt;strong&gt;Опыт&lt;/strong&gt;: &lt;i&gt;{3}&lt;/i&gt;
        ///
        ///&lt;strong&gt;Технологии&lt;/strong&gt;: &lt;i&gt;{4}&lt;/i&gt;
        ///
        ///&lt;strong&gt;Преимущества&lt;/strong&gt;: &lt;i&gt;{5}&lt;/i&gt;
        ///
        ///&lt;strong&gt;Хобби&lt;/strong&gt;: &lt;i&gt;{6}&lt;/i&gt;
        ///
        ///&lt;strong&gt;&lt;a href=&quot;{7}&quot;&gt;Интервью&lt;/a&gt;&lt;/strong&gt;
        ///
        ///&lt;strong&gt;&lt;a href=&quot;{8}&quot;&gt;Профиль GitHub&lt;/a&gt;&lt;/strong&gt;.
        /// </summary>
        public static string AboutCurator {
            get {
                return ResourceManager.GetString("AboutCurator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Студент:
        ///&lt;i&gt;{0} {1}. &lt;/i&gt;
        ///&lt;a href=&quot;{2}&quot;&gt;Профиль GitHub&lt;/a&gt;.
        /// </summary>
        public static string AboutStudent {
            get {
                return ResourceManager.GetString("AboutStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] AddCuratorsTemplate {
            get {
                object obj = ResourceManager.GetObject("AddCuratorsTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] AddGroupsTemplate {
            get {
                object obj = ResourceManager.GetObject("AddGroupsTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] AddStudentsTemplate {
            get {
                object obj = ResourceManager.GetObject("AddStudentsTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ChangeCuratorProfileTemplate {
            get {
                object obj = ResourceManager.GetObject("ChangeCuratorProfileTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для просмотра подробной информации нажмите на кнопку:.
        /// </summary>
        public static string ChooseCurator {
            get {
                return ResourceManager.GetString("ChooseCurator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите записаться к куратору:
        ///{0} {1}?.
        /// </summary>
        public static string ChooseCuratorConfirm {
            get {
                return ResourceManager.GetString("ChooseCuratorConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Студент {0} {1} @{2} записан к вам на курс {3}..
        /// </summary>
        public static string ConfirmCuratorSucsessText {
            get {
                return ResourceManager.GetString("ConfirmCuratorSucsessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мои курсы:.
        /// </summary>
        public static string Courses {
            get {
                return ResourceManager.GetString("Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список кураторов.
        /// </summary>
        public static string CuratorsList {
            get {
                return ResourceManager.GetString("CuratorsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поздравляем!
        ///Вы записаны к куратору:
        ///&lt;i&gt;{0} {1}. &lt;/i&gt;.
        /// </summary>
        public static string CuratorSuccess {
            get {
                return ResourceManager.GetString("CuratorSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполните скачанный шаблон и загрузите файл.
        /// </summary>
        public static string DownloadNewCourse {
            get {
                return ResourceManager.GetString("DownloadNewCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шаблон для скачивания:.
        /// </summary>
        public static string DownloadTemplate {
            get {
                return ResourceManager.GetString("DownloadTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить куратора {0} {1} с курса {2} ?.
        /// </summary>
        public static string RemoveCuratorConfirm {
            get {
                return ResourceManager.GetString("RemoveCuratorConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите действие:.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курс {1}
        /// Дата начала {2}
        ///Дата окончания {3}
        ///Куратор: {4} {5} {6}.
        /// </summary>
        public static string SelectedCourseWithCurator {
            get {
                return ResourceManager.GetString("SelectedCourseWithCurator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курс &lt;i&gt;{0}&lt;/i&gt;.
        ///Дата начала &lt;i&gt;{1}&lt;/i&gt;. 
        ///Дата окончания &lt;i&gt;{2}&lt;/i&gt;..
        /// </summary>
        public static string SelectedCourseWithoutCurator {
            get {
                return ResourceManager.GetString("SelectedCourseWithoutCurator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите группы:.
        /// </summary>
        public static string SelectGroups {
            get {
                return ResourceManager.GetString("SelectGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите кол-во доступных мест к куратору.
        /// </summary>
        public static string SelectWorkloadCount {
            get {
                return ResourceManager.GetString("SelectWorkloadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравствуйте, &lt;i&gt;{0}&lt;/i&gt;! Добро пожаловать в бота по записи на потоковые курсы онлайн школы &lt;a href=&quot;https://ironprogrammer.ru/&quot;&gt;IRON PROGRAMMER&lt;/a&gt;. Выберите направление.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список студентов:.
        /// </summary>
        public static string StudentsList {
            get {
                return ResourceManager.GetString("StudentsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] UploadTemplateNewCourses {
            get {
                object obj = ResourceManager.GetObject("UploadTemplateNewCourses", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка!.
        /// </summary>
        public static string WrongText {
            get {
                return ResourceManager.GetString("WrongText", resourceCulture);
            }
        }
    }
}
